### ISSUE TITLE
Failure in parsing date when accessing /users resource on the machine running in BST timezone

### ISSUE THREAD

**Issue by konstan** [slipstream/SlipStreamUI#246]
In /users resource

```
java.lang.IllegalArgumentException: Invalid format: "2014-09-17 00:21:37.114 BST" is malformed at "BST"

Exception id: 239x33401875204372204310
```

In the jetty start.log:

```
>>>> Uncaught exception during the UI generation (clj side):

java.lang.IllegalArgumentException: Invalid format: "2014-09-17 00:21:37.114 BST" is malformed at "BST"
        at org.joda.time.format.DateTimeFormatter.parseDateTime(DateTimeFormatter.java:873)
        at clj_time.format$parse.invoke(format.clj:153)
        at slipstream.ui.util.time$parse.invoke(time.clj:84)
        at slipstream.ui.util.time$format.invoke(time.clj:150)
        at slipstream.ui.views.table$cell_timestamp_snip_view.invoke(table.clj:161)
        at slipstream.ui.views.table$fn__5313.invoke(table.clj:538)
        at clojure.lang.MultiFn.invoke(MultiFn.java:227)
        at clojure.core$map$fn__4207.invoke(core.clj:2485)
        at clojure.lang.LazySeq.sval(LazySeq.java:42)
        at clojure.lang.LazySeq.seq(LazySeq.java:60)
        at clojure.lang.RT.seq(RT.java:484)
        at clojure.core$seq.invoke(core.clj:133)
        at net.cgrand.enlive_html$flatten_nodes_coll$flat_STAR___136.invoke(enlive_html.clj:227)
        at net.cgrand.enlive_html$flatten_nodes_coll$flat__140$fn__141.invoke(enlive_html.clj:232)
        at clojure.lang.LazySeq.sval(LazySeq.java:42)
        at clojure.lang.LazySeq.seq(LazySeq.java:60)
        at clojure.lang.RT.seq(RT.java:484)
        at clojure.core$seq.invoke(core.clj:133)
        at clojure.core$comp$fn__4154.invoke(core.clj:2331)
        at clojure.zip$children.invoke(zip.clj:80)
        at clojure.zip$down.invoke(zip.clj:116)
        at net.cgrand.enlive_html$children_locs.invoke(enlive_html.clj:417)
        at net.cgrand.enlive_html$transform_loc.invoke(enlive_html.clj:426)
        at net.cgrand.enlive_html$transform_loc$fn__329.invoke(enlive_html.clj:425)
        at clojure.lang.ArrayChunk.reduce(ArrayChunk.java:63)
        at clojure.core.protocols$fn__6041.invoke(protocols.clj:98)
        at clojure.core.protocols$fn__6005$G__6000__6014.invoke(protocols.clj:19)
        at clojure.core.protocols$seq_reduce.invoke(protocols.clj:31)
        at clojure.core.protocols$fn__6024.invoke(protocols.clj:60)
        at clojure.core.protocols$fn__5979$G__5974__5992.invoke(protocols.clj:13)
        at clojure.core$reduce.invoke(core.clj:6177)
        at net.cgrand.enlive_html$mapknitv.invoke(enlive_html.clj:199)
        at net.cgrand.enlive_html$transform_loc.invoke(enlive_html.clj:426)
        at net.cgrand.enlive_html$transform_loc$fn__329.invoke(enlive_html.clj:425)
        at clojure.lang.ArrayChunk.reduce(ArrayChunk.java:63)
        at clojure.core.protocols$fn__6041.invoke(protocols.clj:98)
        at clojure.core.protocols$fn__6005$G__6000__6014.invoke(protocols.clj:19)
        at clojure.core.protocols$seq_reduce.invoke(protocols.clj:31)
        at clojure.core.protocols$fn__6024.invoke(protocols.clj:60)
        at clojure.core.protocols$fn__5979$G__5974__5992.invoke(protocols.clj:13)
        at clojure.core$reduce.invoke(core.clj:6177)
        at net.cgrand.enlive_html$mapknitv.invoke(enlive_html.clj:199)
        at net.cgrand.enlive_html$transform_loc.invoke(enlive_html.clj:426)
        at net.cgrand.enlive_html$transform_loc$fn__329.invoke(enlive_html.clj:425)
        at clojure.lang.ArrayChunk.reduce(ArrayChunk.java:58)
        at clojure.core.protocols$fn__6041.invoke(protocols.clj:98)
        at clojure.core.protocols$fn__6005$G__6000__6014.invoke(protocols.clj:19)
        at clojure.core.protocols$seq_reduce.invoke(protocols.clj:31)
        at clojure.core.protocols$fn__6024.invoke(protocols.clj:60)
        at clojure.core.protocols$fn__5979$G__5974__5992.invoke(protocols.clj:13)
        at clojure.core$reduce.invoke(core.clj:6177)
        at net.cgrand.enlive_html$mapknitv.invoke(enlive_html.clj:199)
        at net.cgrand.enlive_html$transform_loc.invoke(enlive_html.clj:426)
        at net.cgrand.enlive_html$transform_loc$fn__329.invoke(enlive_html.clj:425)
        at clojure.lang.ArrayChunk.reduce(ArrayChunk.java:63)
        at clojure.core.protocols$fn__6041.invoke(protocols.clj:98)
        at clojure.core.protocols$fn__6005$G__6000__6014.invoke(protocols.clj:19)
        at clojure.core.protocols$seq_reduce.invoke(protocols.clj:31)
        at clojure.core.protocols$fn__6024.invoke(protocols.clj:60)
        at clojure.core.protocols$fn__5979$G__5974__5992.invoke(protocols.clj:13)
        at clojure.core$reduce.invoke(core.clj:6177)
        at net.cgrand.enlive_html$mapknitv.invoke(enlive_html.clj:199)
        at net.cgrand.enlive_html$transform_loc.invoke(enlive_html.clj:426)
        at net.cgrand.enlive_html$transform_loc$fn__329.invoke(enlive_html.clj:425)
        at clojure.lang.ArrayChunk.reduce(ArrayChunk.java:63)
        at clojure.core.protocols$fn__6041.invoke(protocols.clj:98)
        at clojure.core.protocols$fn__6005$G__6000__6014.invoke(protocols.clj:19)
        at clojure.core.protocols$seq_reduce.invoke(protocols.clj:31)
        at clojure.core.protocols$fn__6024.invoke(protocols.clj:60)
        at clojure.core.protocols$fn__5979$G__5974__5992.invoke(protocols.clj:13)
        at clojure.core$reduce.invoke(core.clj:6177)
        at net.cgrand.enlive_html$mapknitv.invoke(enlive_html.clj:199)
        at net.cgrand.enlive_html$transform_loc.invoke(enlive_html.clj:426)
        at net.cgrand.enlive_html$transform_node$fn__338.invoke(enlive_html.clj:441)
        at clojure.lang.ArrayChunk.reduce(ArrayChunk.java:58)
        at clojure.core.protocols$fn__6041.invoke(protocols.clj:98)
        at clojure.core.protocols$fn__6005$G__6000__6014.invoke(protocols.clj:19)
        at clojure.core.protocols$seq_reduce.invoke(protocols.clj:31)
        at clojure.core.protocols$fn__6024.invoke(protocols.clj:60)
        at clojure.core.protocols$fn__5979$G__5974__5992.invoke(protocols.clj:13)
        at clojure.core$reduce.invoke(core.clj:6177)
        at net.cgrand.enlive_html$mapknitv.invoke(enlive_html.clj:199)
        at net.cgrand.enlive_html$transform_node.invoke(enlive_html.clj:441)
        at net.cgrand.enlive_html$transform.invoke(enlive_html.clj:485)
        at slipstream.ui.views.section$fn__6112$fn__6114$fn__6115$fn__6116$iter__6117__6121$fn__6122$fn__6123.invoke(section.clj:38)
        at slipstream.ui.views.section$fn__6112$fn__6114$fn__6115$fn__6116$iter__6117__6121$fn__6122.invoke(section.clj:24)
        at clojure.lang.LazySeq.sval(LazySeq.java:42)
        at clojure.lang.LazySeq.seq(LazySeq.java:60)
        at clojure.lang.RT.seq(RT.java:484)
        at clojure.core$seq.invoke(core.clj:133)
        at clojure.core$interleave$fn__4525.invoke(core.clj:3901)
        at clojure.lang.LazySeq.sval(LazySeq.java:42)
        at clojure.lang.LazySeq.seq(LazySeq.java:60)
        at clojure.lang.RT.seq(RT.java:484)
        at clojure.core$seq.invoke(core.clj:133)
        at clojure.core$drop$step__4240.invoke(core.clj:2574)
        at clojure.core$drop$fn__4243.invoke(core.clj:2578)
        at clojure.lang.LazySeq.sval(LazySeq.java:42)
        at clojure.lang.LazySeq.seq(LazySeq.java:60)
        at clojure.lang.LazySeq.cons(LazySeq.java:103)
        at clojure.lang.LazySeq.cons(LazySeq.java:17)
        at clojure.lang.RT.conj(RT.java:562)
        at clojure.core$conj.invoke(core.clj:83)
        at slipstream.ui.views.section$fn__6112$fn__6114$fn__6115$fn__6116.invoke(section.clj:24)
        at net.cgrand.enlive_html$transform_loc.invoke(enlive_html.clj:430)
        at net.cgrand.enlive_html$transform_node$fn__338.invoke(enlive_html.clj:441)
        at clojure.lang.ArrayChunk.reduce(ArrayChunk.java:58)
        at clojure.core.protocols$fn__6041.invoke(protocols.clj:98)
        at clojure.core.protocols$fn__6005$G__6000__6014.invoke(protocols.clj:19)
        at clojure.core.protocols$seq_reduce.invoke(protocols.clj:31)
        at clojure.core.protocols$fn__6024.invoke(protocols.clj:60)
        at clojure.core.protocols$fn__5979$G__5974__5992.invoke(protocols.clj:13)
        at clojure.core$reduce.invoke(core.clj:6177)
        at net.cgrand.enlive_html$mapknitv.invoke(enlive_html.clj:199)
        at net.cgrand.enlive_html$transform_node.invoke(enlive_html.clj:441)
        at net.cgrand.enlive_html$transform.invoke(enlive_html.clj:485)
        at slipstream.ui.views.section$fn__6112$fn__6114$fn__6115.invoke(section.clj:22)
        at clojure.core$map$fn__4207.invoke(core.clj:2487)
        at clojure.lang.LazySeq.sval(LazySeq.java:42)
        at clojure.lang.LazySeq.seq(LazySeq.java:60)
        at clojure.lang.RT.seq(RT.java:484)
        at clojure.core$seq.invoke(core.clj:133)
        at net.cgrand.enlive_html$flatten_nodes_coll$flat_STAR___136.invoke(enlive_html.clj:227)
        at net.cgrand.enlive_html$flatten_nodes_coll$flat__140$fn__141.invoke(enlive_html.clj:232)
        at clojure.lang.LazySeq.sval(LazySeq.java:42)
        at clojure.lang.LazySeq.seq(LazySeq.java:60)
        at clojure.lang.RT.seq(RT.java:484)
        at clojure.core$seq.invoke(core.clj:133)
        at clojure.core$dorun.invoke(core.clj:2780)
        at clojure.core$doall.invoke(core.clj:2796)
        at slipstream.ui.views.section$fn__6112$fn__6114.invoke(section.clj:22)
        at slipstream.ui.views.section$build.invoke(section.clj:46)
        at slipstream.ui.views.base$transform_content.invoke(base.clj:151)
        at slipstream.ui.views.base$fn__6570$fn__6573$fn__6576.invoke(base.clj:216)
        at clojure.core$map$fn__4207.invoke(core.clj:2485)
        at clojure.lang.LazySeq.sval(LazySeq.java:42)
        at clojure.lang.LazySeq.seq(LazySeq.java:60)
        at clojure.lang.RT.seq(RT.java:484)
        at clojure.core$seq.invoke(core.clj:133)
        at net.cgrand.enlive_html$flatten_nodes_coll$flat_STAR___136.invoke(enlive_html.clj:227)
        at net.cgrand.enlive_html$flatten_nodes_coll$flat__140$fn__141.invoke(enlive_html.clj:232)
        at clojure.lang.LazySeq.sval(LazySeq.java:42)
        at clojure.lang.LazySeq.seq(LazySeq.java:60)
        at clojure.lang.RT.seq(RT.java:484)
        at clojure.core$seq.invoke(core.clj:133)
        at clojure.core$dorun.invoke(core.clj:2780)
        at clojure.core$doall.invoke(core.clj:2796)
        at slipstream.ui.views.base$fn__6570$fn__6573.invoke(base.clj:166)
        at clojure.core$comp$fn__4154.invoke(core.clj:2331)
        at slipstream.ui.views.base$generate_with_ns.invoke(base.clj:272)
        at slipstream.ui.views.users$page.invoke(users.clj:21)
        at clojure.lang.AFn.applyToHelper(AFn.java:161)
        at clojure.lang.AFn.applyTo(AFn.java:151)
        at clojure.core$apply.invoke(core.clj:617)
        at slipstream.ui.views.representation$render_html.doInvoke(representation.clj:72)
        at clojure.lang.RestFn.invoke(RestFn.java:423)
        at slipstream.ui.views.representation$render_page.invoke(representation.clj:78)
        at slipstream.ui.views.representation$_toHtml.invoke(representation.clj:120)
        at slipstream.ui.views.Representation.toHtml(Unknown Source)
        at com.sixsq.slipstream.util.HtmlUtil.toHtml(HtmlUtil.java:61)
        at com.sixsq.slipstream.util.HtmlUtil.toHtml(HtmlUtil.java:43)
        at com.sixsq.slipstream.user.UserListResource.toHtml(UserListResource.java:66)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:606)
        at org.restlet.resource.ServerResource.doHandle(ServerResource.java:524)
        at org.restlet.resource.ServerResource.get(ServerResource.java:743)
        at org.restlet.resource.ServerResource.doHandle(ServerResource.java:618)
        at org.restlet.resource.ServerResource.doNegotiatedHandle(ServerResource.java:679)
        at org.restlet.resource.ServerResource.doConditionalHandle(ServerResource.java:357)
        at org.restlet.resource.ServerResource.handle(ServerResource.java:1014)
        at org.restlet.resource.Finder.handle(Finder.java:246)
        at org.restlet.routing.Filter.doHandle(Filter.java:159)
        at org.restlet.routing.Filter.handle(Filter.java:206)
        at org.restlet.routing.Filter.doHandle(Filter.java:159)
        at org.restlet.routing.Filter.handle(Filter.java:206)
        at org.restlet.routing.Router.doHandle(Router.java:431)
        at org.restlet.routing.Router.handle(Router.java:648)
        at org.restlet.routing.Filter.doHandle(Filter.java:159)
        at org.restlet.routing.Filter.handle(Filter.java:206)
        at org.restlet.routing.Filter.doHandle(Filter.java:159)
        at org.restlet.routing.Filter.handle(Filter.java:206)
        at org.restlet.routing.Filter.doHandle(Filter.java:159)
        at org.restlet.routing.Filter.handle(Filter.java:206)
        at org.restlet.routing.Router.doHandle(Router.java:431)
        at com.sixsq.slipstream.application.RootApplication$RootRouter.doHandle(RootApplication.java:402)
        at org.restlet.routing.Router.handle(Router.java:648)
        at org.restlet.routing.Filter.doHandle(Filter.java:159)
        at org.restlet.routing.Filter.handle(Filter.java:206)
        at org.restlet.routing.Filter.doHandle(Filter.java:159)
        at org.restlet.routing.Filter.handle(Filter.java:206)
        at org.restlet.routing.Filter.doHandle(Filter.java:159)
        at org.restlet.routing.Filter.handle(Filter.java:206)
        at org.restlet.routing.Filter.doHandle(Filter.java:159)
        at org.restlet.engine.application.StatusFilter.doHandle(StatusFilter.java:155)
        at org.restlet.routing.Filter.handle(Filter.java:206)
        at org.restlet.routing.Filter.doHandle(Filter.java:159)
        at org.restlet.routing.Filter.handle(Filter.java:206)
        at org.restlet.engine.CompositeHelper.handle(CompositeHelper.java:211)
        at org.restlet.engine.application.ApplicationHelper.handle(ApplicationHelper.java:84)
        at org.restlet.Application.handle(Application.java:384)
        at org.restlet.routing.Filter.doHandle(Filter.java:159)
        at org.restlet.routing.Filter.handle(Filter.java:206)
        at org.restlet.routing.Router.doHandle(Router.java:431)
        at org.restlet.routing.Router.handle(Router.java:648)
        at org.restlet.routing.Filter.doHandle(Filter.java:159)
        at org.restlet.routing.Filter.handle(Filter.java:206)
        at org.restlet.routing.Router.doHandle(Router.java:431)
        at org.restlet.routing.Router.handle(Router.java:648)
        at org.restlet.routing.Filter.doHandle(Filter.java:159)
        at org.restlet.routing.Filter.handle(Filter.java:206)
        at org.restlet.engine.CompositeHelper.handle(CompositeHelper.java:211)
        at org.restlet.Component.handle(Component.java:406)
        at org.restlet.Server.handle(Server.java:516)
        at org.restlet.engine.connector.ServerHelper.handle(ServerHelper.java:72)
        at org.restlet.engine.adapter.HttpServerHelper.handle(HttpServerHelper.java:152)
        at org.restlet.ext.servlet.ServerServlet.service(ServerServlet.java:1118)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:848)
        at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:698)
        at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:519)
        at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:138)
        at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:564)
        at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:213)
        at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1097)
        at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:446)
        at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:175)
        at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1031)
        at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:136)
        at org.eclipse.jetty.server.handler.ContextHandlerCollection.handle(ContextHandlerCollection.java:200)
        at org.eclipse.jetty.server.handler.HandlerCollection.handle(HandlerCollection.java:109)
        at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:97)
        at org.eclipse.jetty.server.Server.handle(Server.java:445)
        at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:269)
        at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:229)
        at org.eclipse.jetty.io.AbstractConnection$ReadCallback.run(AbstractConnection.java:358)
        at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:601)
        at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:532)
        at java.lang.Thread.run(Thread.java:745)
```

**Comment by rbf** [comment]
Fix on its way.

**Comment by konstan** [comment]
Cool.  If you don't push it to master, please push let me know what branch it is fixed on.   I'll build it manually.  (I need this for CELAR.)

**Comment by konstan** [comment]
I see this on module resources as well :(

**Comment by rbf** [comment]
> I see this on module resources as well :(

Yes, the function to parse and format timestamps is the same everywhere.
