### ISSUE TITLE
NullPointerException when a deployment parameter is renamed or when one is added an one is removed

### ISSUE THREAD

**Issue by schaubl** [slipstream/SlipStreamUI#343]
```
>>>> Uncaught exception during the UI generation (clj side):

java.lang.NullPointerException
        at clojure.core$name.invoke(core.clj:1518)
        at slipstream.ui.views.subsection$assoc_id.invoke(subsection.clj:72)
        at clojure.lang.AFn.applyToHelper(AFn.java:156)
        at clojure.lang.AFn.applyTo(AFn.java:144)
        at clojure.core$apply.invoke(core.clj:626)
        at clojure.core$partial$fn__4228.doInvoke(core.clj:2468)
        at clojure.lang.RestFn.invoke(RestFn.java:408)
        at clojure.core$map$fn__4245.invoke(core.clj:2557)
        at clojure.lang.LazySeq.sval(LazySeq.java:40)
        at clojure.lang.LazySeq.seq(LazySeq.java:49)
        at clojure.lang.RT.seq(RT.java:484)
        at clojure.lang.RT.countFrom(RT.java:537)
        at clojure.lang.RT.count(RT.java:530)
        at slipstream.ui.views.subsection$subsection_group_snip.invoke(subsection.clj:65)
        at slipstream.ui.views.subsection$build.invoke(subsection.clj:79)
        at slipstream.ui.views.section$fn__6141$fn__6143$fn__6144$fn__6145$iter__6146__6150$fn__6151.invoke(section.clj:37)
        at clojure.lang.LazySeq.sval(LazySeq.java:40)
        at clojure.lang.LazySeq.seq(LazySeq.java:49)
        at clojure.lang.RT.seq(RT.java:484)
        at clojure.core$seq.invoke(core.clj:133)
        at clojure.core$interleave$fn__4566.invoke(core.clj:3973)
        at clojure.lang.LazySeq.sval(LazySeq.java:40)
        at clojure.lang.LazySeq.seq(LazySeq.java:49)
        at clojure.lang.Cons.next(Cons.java:39)
        at clojure.lang.PersistentVector.create(PersistentVector.java:51)
        at clojure.lang.LazilyPersistentVector.create(LazilyPersistentVector.java:31)
        at clojure.core$vec.invoke(core.clj:354)
        at slipstream.ui.views.section$fn__6141$fn__6143$fn__6144$fn__6145.invoke(section.clj:25)
        at net.cgrand.enlive_html$transform_loc.invoke(enlive_html.clj:430)
        at net.cgrand.enlive_html$transform_node$fn__338.invoke(enlive_html.clj:441)
        at clojure.lang.ArrayChunk.reduce(ArrayChunk.java:58)
        at clojure.core.protocols$fn__6093.invoke(protocols.clj:98)
        at clojure.core.protocols$fn__6057$G__6052__6066.invoke(protocols.clj:19)
        at clojure.core.protocols$seq_reduce.invoke(protocols.clj:31)
        at clojure.core.protocols$fn__6076.invoke(protocols.clj:60)
        at clojure.core.protocols$fn__6031$G__6026__6044.invoke(protocols.clj:13)
        at clojure.core$reduce.invoke(core.clj:6289)
        at net.cgrand.enlive_html$mapknitv.invoke(enlive_html.clj:199)
        at net.cgrand.enlive_html$transform_node.invoke(enlive_html.clj:441)
        at net.cgrand.enlive_html$transform.invoke(enlive_html.clj:485)
        at slipstream.ui.views.section$fn__6141$fn__6143$fn__6144.invoke(section.clj:24)
        at clojure.core$map$fn__4245.invoke(core.clj:2559)
        at clojure.lang.LazySeq.sval(LazySeq.java:40)
        at clojure.lang.LazySeq.seq(LazySeq.java:49)
        at clojure.lang.RT.seq(RT.java:484)
        at clojure.core$seq.invoke(core.clj:133)
        at net.cgrand.enlive_html$flatten_nodes_coll$flat_STAR___136.invoke(enlive_html.clj:227)
        at net.cgrand.enlive_html$flatten_nodes_coll$flat__140$fn__141.invoke(enlive_html.clj:232)
        at clojure.lang.LazySeq.sval(LazySeq.java:40)
        at clojure.lang.LazySeq.seq(LazySeq.java:49)
```

**Comment by schaubl** [comment]
Here is an XML which breaks the UI: https://slipstream.sixsq.com/module/apps/Torque/torque-master/1786?media=xml

It seems that some parameters are missing the Category:
```xml
<parameter category="Output" description="hostname/ip of the image" isSet="false" mandatory="true" name="hostname" order="0" order_="0" readonly="false" type="String"/>
<parameter description="SSH Key (RSA) base64 encoded" isSet="false" mandatory="false" name="ssh_key_rsa_b64" order="0" order_="0" readonly="false" type="String"/>
<parameter description="Munge key base64 encoded" isSet="false" mandatory="false" name="munge_key_b64" order="0" order_="0" readonly="false" type="String"/>
<parameter category="Input" description="Name of the node based on the image torque-worker" isSet="false" mandatory="false" name="torque-worker_nodename" order="0" order_="0" readonly="false" type="String"/>
<parameter category="Output" description="Cloud instance id" isSet="false" mandatory="true" name="instanceid" order="0" order_="0" readonly="false" type="String"/>
```

**Comment by rbf** [comment]
@schaubl 
Parameter updates are not well supported server side.
Would you agree if we disabled editing of existent parameter names, i.e. the same way we disable changing the category?

I mean, going from the current behaviour:

![screen shot 2015-07-14 at 16 02 16](https://cloud.githubusercontent.com/assets/807084/8675058/04d88842-2a42-11e5-8c86-1a452912bff4.png)

into this one:

![screen shot 2015-07-14 at 16 14 30](https://cloud.githubusercontent.com/assets/807084/8675325/829ff764-2a43-11e5-93c1-3721063c5a94.png)

**Comment by schaubl** [comment]
I don't see the difference.
If the issue is only with the `name`, removing one and adding a new one with a different name should be seen exactly the same way by the server.

**Comment by rbf** [comment]
> I don't see the difference.

In the second screenshot, the first column is only editable in the last column(s).

> If the issue is only with the name, removing one and adding a new one with a different name should be seen exactly the same way by the server.

I don't understand this, sorry.

**Comment by schaubl** [comment]
> In the second screenshot, the first column is only editable in the last column(s).
I can see this but I meant that I don't see what it will change server side.

> I don't understand this, sorry.
For the the server will receive the same request if I :
1. Rename the parameter A to B
2. Remove the parameter A and create the parameter B

**Comment by rbf** [comment]
Got it:
2. works as expected.
The problem happens with 1, because the `Category` is not sent because is not displayed as editable.
Thanks for your explanations :bow:

**Comment by schaubl** [comment]
Is there a way to send the `Category` all the time ?

**Comment by rbf** [comment]
Indeed, that's what I'm doing. Sorry, should have add this to my previous comment.
